server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /logs {
        proxy_pass ${BE_URL}/logs;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding off;
    }

    location ~ ^/(status|control)$ {
        proxy_pass ${BE_URL};
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
